FROM node:22-alpine
WORKDIR /usr/src/app
COPY package*.json ./
 
RUN apk add --no-cache vips-dev build-base && \
    npm install && \
    apk del build-base

COPY . .

# No EXPOSE needed if it's purely a consumer, but might have health check endpoint
EXPOSE 5001
# Example for a health check endpoint
CMD ["npm", "start"]

