FROM node:22-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache curl
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5001
 # Or whatever port your Express app listens on

CMD ["node", "app.js"]
